# Generated by Django 4.2.4 on 2023-08-30 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turflocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turflocation', models.CharField(max_length=50)),
                ('turfaddress', models.CharField(max_length=50)),
                ('turfimage', models.ImageField(default='null.jpg', upload_to='data')),
            ],
        ),
        migrations.CreateModel(
            name='Extraimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additionalimages', models.ImageField(default='null.jpg', upload_to='data')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.turflocation')),
            ],
        ),
    ]
