# Generated by Django 4.2.4 on 2023-08-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_turflocation_extraimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='turflocation',
            name='placeprice',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
