# Generated by Django 4.2.4 on 2023-08-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_turflocation_placeprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turfcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, null=True)),
                ('categoryprice', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
