# Generated by Django 4.2.4 on 2023-08-31 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_turfcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districtname', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='turflocation',
            name='turflocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.districts'),
        ),
    ]
