# Generated by Django 4.2.4 on 2023-08-31 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_districts_alter_turflocation_turflocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
