# Generated by Django 4.2.4 on 2023-08-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_delete_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='turflocation',
            name='tname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
