# Generated by Django 4.2.4 on 2023-09-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Managerregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managerfname', models.CharField(max_length=50)),
                ('managerlname', models.CharField(max_length=50)),
                ('manageraddress', models.CharField(max_length=50)),
                ('managercities', models.CharField(max_length=50)),
                ('managerphone', models.CharField(max_length=50)),
                ('manageremail', models.CharField(max_length=50)),
                ('managerpassword', models.CharField(max_length=50)),
                ('managerstatus', models.CharField(default=0, max_length=50)),
            ],
        ),
    ]
