# Generated by Django 4.2.4 on 2023-09-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerregister',
            name='designation',
            field=models.CharField(default='manager', max_length=50),
        ),
    ]
