# Generated by Django 4.2.4 on 2023-09-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_managerregister_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerregister',
            name='assignedturf',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
